services:
  personal-site-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: personal-site-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules